// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFfNo6kBHhlAPfZFG59PPQJ94i8I6w3U',
    appId: '1:893864573731:web:cf3a0e8494759ce603aa96',
    messagingSenderId: '893864573731',
    projectId: 'flutterfireadmin',
    authDomain: 'flutterfireadmin.firebaseapp.com',
    databaseURL: 'https://flutterfireadmin-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfireadmin.firebasestorage.app',
    measurementId: 'G-9KJZVGLJ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgUM7kmLj_snyjKGOjrob62adnyWefEg',
    appId: '1:893864573731:android:ed8e3c8856c0c10b03aa96',
    messagingSenderId: '893864573731',
    projectId: 'flutterfireadmin',
    databaseURL: 'https://flutterfireadmin-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfireadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbC4WmDqWbS97ta_QG4LSAecdYDYqiFw',
    appId: '1:893864573731:ios:a67a1d3b82e4154b03aa96',
    messagingSenderId: '893864573731',
    projectId: 'flutterfireadmin',
    databaseURL: 'https://flutterfireadmin-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfireadmin.firebasestorage.app',
    iosBundleId: 'com.example.crudNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmbC4WmDqWbS97ta_QG4LSAecdYDYqiFw',
    appId: '1:893864573731:ios:a67a1d3b82e4154b03aa96',
    messagingSenderId: '893864573731',
    projectId: 'flutterfireadmin',
    databaseURL: 'https://flutterfireadmin-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfireadmin.firebasestorage.app',
    iosBundleId: 'com.example.crudNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgFfNo6kBHhlAPfZFG59PPQJ94i8I6w3U',
    appId: '1:893864573731:web:f2d2df8f76c40d1803aa96',
    messagingSenderId: '893864573731',
    projectId: 'flutterfireadmin',
    authDomain: 'flutterfireadmin.firebaseapp.com',
    databaseURL: 'https://flutterfireadmin-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfireadmin.firebasestorage.app',
    measurementId: 'G-00X521SMR2',
  );
}
